export const icons = [
  {
    name: "Dashboard",
    title: "Users Dashboard",
    link: "/dashboard",
    active: "/active_dashboard.svg",
    inactive: "/inactive_dashboard.svg",
    index: 1,
  },
  {
    name: "Users",
    title: "Users",
    link: "/users",
    active: "/active_users.svg",
    inactive: "/inactive_users.svg",
    index: 2,
  },
  {
    name: "Documents",
    title: "Documents",
    link: "/documents",
    active: "/active_documents.svg",
    inactive: "/inactive_documents.svg",
    index: 3,
  },
  {
    name: "Photos",
    title: "Photos",
    link: "/photos",
    active: "/active_photos.svg",
    inactive: "/inactive_photos.svg",
    index: 4,
  },
  {
    name: "Hierarchy",
    title: "Hierarchy",
    link: "/hierarchy",
    active: "/active_hierarchy.svg",
    inactive: "/inactive_hierarchy.svg",
    index: 5,
  },

  {
    name: "Message",
    title: "",
    link: "/message",
    active: "/active_message.svg",
    inactive: "/inactive_message.svg",
    index: 6,
  },
  {
    name: "Help",
    title: "",
    link: "/help",
    active: "/active_help.svg",
    inactive: "/inactive_help.svg",
    index: 7,
  },
  {
    name: "Setting",
    title: "",
    link: "/setting",
    active: "/active_setting.svg",
    inactive: "/inactive_setting.svg",
    index: 8,
  },
];
export const documentsIcon = [
  { link: "first.svg" },
  { link: "second.svg" },
  { link: "third.svg" },
  { link: "fourth.svg" },
  { link: "fifth.svg" },
];
